site_name: Sensor Fusion Documentation
pages:
- Home: 'index.md'
- User Guide:
    - 'Installation': 'installation.md'
    - 'Quick Start': 'start.md'
    - 'Evaluation' : 'evaluation.md'
- Code Reference:
    - 'Cloud_crop': 'code/cloud_crop.md'
    - 'Clustering': 'code/clustering.md'
    - 'Lidar_oject_fusion': 'code/fusion1.md'
    - 'Cluster_camera_fusion': 'code/fusion2.md'
    - 'Lidar_camera_fusion': 'code/lidar_camera.md'
    - 'sensor_fusion_msg':
        - 'CameraObjects': 'code/msg/cameraObjects.md'
        - 'FusedObjectsMsg': 'code/msg/fusedObject.md'
        - 'LidarClusters': 'code/msg/LidarClusters.md'
        - 'MappedPointMsg': 'code/msg/MappedPoint.md'
        - 'ObjectBoundingBox': 'code/msg/ObjectBoundingBox.md'
- Portfolio:
    - 'Documents': 'docs.md'
- About:
    - 'About': 'about.md'
theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Orange'
use_directory_urls: false
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.arithmatex
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true