site_name: Sensor Fusion Documentation
nav:
- Home: 'index.md'
- Tech Report:
  - User Guide:
      - 'Installation': 'Tech Report/Documentation/installation.md'
      - 'Quick Start': 'Tech Report/Documentation/start.md'
      - 'Evaluation' : 'Tech Report/Documentation/evaluation.md'
  - Code:
      - 'Code Overview': 'Tech Report/Documentation/code/code.md'
      - 'Cloud_crop': 'Tech Report/Documentation/code/cloud_crop.md'
      - 'Clustering': 'Tech Report/Documentation/code/clustering.md'
      - 'Lidar_oject_fusion': 'Tech Report/Documentation/code/fusion1.md'
      - 'Cluster_camera_fusion': 'Tech Report/Documentation/code/fusion2.md'
      - 'Lidar_camera_fusion': 'Tech Report/Documentation/code/lidar_camera.md'
      - 'sensor_fusion_msg':
          - 'CameraObjects': 'Tech Report/Documentation/code/msg/cameraObjects.md'
          - 'FusedObjectsMsg': 'Tech Report/Documentation/code/msg/fusedObjects.md'
          - 'LidarClusters': 'Tech Report/Documentation/code/msg/LidarClusters.md'
          - 'MappedPointMsg': 'Tech Report/Documentation/code/msg/MappedPoint.md'
          - 'ObjectBoundingBox': 'Tech Report/Documentation/code/msg/ObjectBoundingBox.md'
  - Reports: 'Tech Report/Reports/reports.md'
  - Test Data: 'Tech Report/Test Data/test_data.md'
  - Results: 'Tech Report/Results/results.md'
  - Pictures: 'Tech Report/Pictures/pictures.md'
  - Datasheets: "Tech Report/Datasheets/datasheets.md"
  - Schemas: 'Tech Report/Schemas/schemas.md'
- Administration:
    - 'Documents': 'Administration/docs.md'
- Papers:
    - Papers: 'Papers/papers.md'
- Presentations:
    - 'Presentations': 'Presentations/presentations.md'
    - 'Videos': 'Presentations/videos.md'
- Resources:
  - Resources: 'Resources/resources.md'
- 'About': 'Administration/about.md'
theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Orange'
  feature:
    tabs: true
google_analytics:
  - 'UA-31328111-2'
  - 'auto'
use_directory_urls: false
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.arithmatex
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true