site_name: Sensor Fusion Documentation
pages:
- Home: 'index.md'
- User Guide:
    - 'Installation': 'installation.md'
    - 'Quick Start': 'start.md'
    - 'Evaluation' : 'evaluation.md'
- Code Reference:
    - 'cloud_crop': 'code/cloud_crop.md'
    - 'Clustering': 'code/clustering.md'
    - 'Fusion 1: camera based': 'code/fusion1.md'
    - 'Fusion 2: cluster based': 'code/fusion2.md'
    - 'Lidar_camera_fusion': 'code/lidar_camera.md'
- Portfolio:
    - 'Documents': 'docs.md'
- About:
    - 'About': 'about.md'
theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Orange'
use_directory_urls: false
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.arithmatex
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true